"""empty message

Revision ID: 0fdf51811228
Revises: 1db0c6cbe8bb
Create Date: 2024-03-04 17:25:04.719470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fdf51811228'
down_revision = '1db0c6cbe8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))
        batch_op.drop_column('account_confirmation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_confirmation', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('confirmed')
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
